### PR TITLE
FIO tx history fixes

### LINKED ISSUE #1000: FIO history: not all TXs are returned
curl `https://blockatlas.trustwallet.com/v1/fio/FIO6XKiobBGrmPZDaHne47TF25CamjFc3cRe8hs7oAiCN59TbJzes`

```json
{
	"total": 1,
	"docs": [{
		"id": "7fe6bfdc3e536ce2fec7623273b68b9e496f04c12d0e9426ab6d5a0a59c06467",
		"coin": 235,
		"from": "rpxtnpsr3gxd",
		"to": "fio.treasury",
		"fee": "0",
		"date": 1585871869,
		"block": 1553003,
		"status": "completed",
		"type": "transfer",
		"direction": "outgoing",
		"memo": "FIO API fees. Thank you.",
		"metadata": {
			"value": "2000000000",
			"symbol": "FIO",
			"decimals": 9
		}
	}],
	"status": true
}
```

The correct value is 5 FIO, fee is 2 FIO :
https://explorer.fioprotocol.io/transaction/7fe6bfdc3e536ce2fec7623273b68b9e496f04c12d0e9426ab6d5a0a59c06467

### PR DESCRIPTION
**Pull request by catenocrypt**
FIO tx history fixes, fixes #1000 .
- include pos+offset in history call to FIO API, to limit size
- switch to fio.greymass.com API, seems more complete with history
- also handle "trnsfiopubky" actions as transfers.

### CODE REVIEW

File: platform/fio/transaction.go [hunk 1]
```diff
@@ -30,28 +30,47 @@ func (p *Platform) GetTxsByAddress(address string) (page blockatlas.TxPage, err
...
-			amount = blockatlas.Amount(strconv.Itoa(int(amountNum * 1000000000)))
+		switch action.ActionTrace.Act.Name {
+		case "transfer":
+			var actionData ActionDataTransfer
+			if json.Unmarshal(dataJSON, &actionData) != nil {
+				return blockatlas.Tx{}, errors.E("Unparseable Data field")
+			}
+			from = actionData.From
+			to = actionData.To
+			amountNum, err := strconv.ParseFloat(strings.Split(actionData.Quantity, " ")[0], 64)
```
Comment (hewigovens) [inline platform/fio/transaction.go:55]: can we unmarshal as `Amount` directly?

Comment (catenocrypt) [reply platform/fio/transaction.go:55]: No, as it is a formatted string, doesn't make much sense
"200.000000000 FIO"
