### PR TITLE
[Tezos] Adopt new block api url

### LINKED ISSUE #1351: [Tezos] Block parsing is not working
## Summary of Bug

```
ERRO[0346] Client Errors                                 fingerprint="[client_errors]" tags="[{status_code 400} {host api.tzstats.com} {url https://api.tzstats.com/explorer/account/1256295/op?limit=5000&type=transaction%2Cdelegation}]"
WARN[0346] retry GetBlockByNumber                        attempts=4 number=1256295 sleep=6.369111973s symbol=XTZ
ERRO[0346] Client Errors                                 fingerprint="[client_errors]" tags="[{status_code 400} {host api.tzstats.com} {url https://api.tzstats.com/explorer/account/1256294/op?limit=5000&type=transaction%2Cdelegation}]"
WARN[0346] retry GetBlockByNumber                        attempts=4 number=1256294 sleep=5.590058627s symbol=XTZ
ERRO[0351] Client Errors                                 fingerprint="[client_errors]" tags="[{status_code 400} {host api.tzstats.com} {url https://api.tzstats.com/explorer/account/1256294/op?limit=5000&type=transaction%2Cdelegation}]"
WARN[0351] retry GetBlockByNumber                        attempts=3 number=1256294 sleep=14.530237681s symbol=XTZ
ERRO[0352] Client Errors                                 fingerprint="[client_errors]" tags="[{status_code 400} {host api.tzstats.com} {url https://api.tzstats.com/explorer/account/1256295/op?limit=5000&type=transaction%2Cdelegation}]"
WARN[0352] retry GetBlockByNumber                        attempts=3 number=1256295 sleep=16.976587819s symbol=XTZ
ERRO[0366] Client Errors                                 fingerprint="[client_errors]" tags="[{status_code 400} {host api.tzstats.com} {url https://api.tzstats.com/explorer/account/1256294/op?limit=5000&type=transaction%2Cdelegation}]"
WARN[0366] retry GetBlockByNumber                        attempts=2 number=1256294 sleep=40.906834777s symbol=XTZ
ERRO[0369] Client Errors                                 fingerprint="[client_errors]" tags="[{status_code 400} {host api.tzstats.com} {url https://api.tzstats.com/explorer/account/1256295/op?limit=5000&type=transaction%2Cdelegation}]"
WARN[0369] retry GetBlockByNumber                        attempts=2 number=1256295 sleep=35.91395051s symbol=XTZ
ERRO[0405] Client Errors                                 fingerprint="[client_errors]" tags="[{status_code 400} {host api.tzstats.com} {url https://api.tzstats.com/explorer/account/1256295/op?limit=5000&type=transaction%2Cdelegation}]"
WARN[0405] retry GetBlockByNumber                        attempts=1 number=1256295 sleep=1m11.836528415s symbol=XTZ
ERRO[0407] Client Errors                                 fingerprint="[client_errors]" tags="[{status_code 400} {host api.tzstats.com} {url https://api.tzstats.com/explorer/account/1256294/op?limit=5000&type=transaction%2Cdelegation}]"
WARN[0407] retry GetBlockByNumber                        attempts=1 number=1256294 sleep=1m58.420543522s symbol=XTZ

```

### PR DESCRIPTION
**Pull request by hewigovens**
Fixes #1351 

https://blockatlas-xt-tezos-blo-rvzdzr.herokuapp.com/v2/tezos/blocks/1292516 works now

### CODE REVIEW

**Review by vikmeup — APPROVED** [review]

File: platform/tezos/client.go [hunk 1]
```diff
@@ -30,13 +30,13 @@ func (c *Client) GetCurrentBlock() (int64, error) {
 }
 
 func (c *Client) GetBlockByNumber(num int64, txType []string) ([]Transaction, error) {
-	var blockOps ExplorerAccount
-	path := fmt.Sprintf("account/%d/op", num)
+	var blockOps []Transaction
```
Comment (vikmeup) [inline platform/tezos/client.go:33]: do we still need `ExplorerAccount` ?

Comment (hewigovens) [reply platform/tezos/client.go:33]: I think so, used in `GetTxsOfAddress`
